# Generated by Django 5.2.4 on 2025-08-25 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredvoter',
            name='names',
            field=models.TextField(help_text='Enter each eligible voter name on a separate line'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='registered_list',
            field=models.ForeignKey(blank=True, help_text='The eligible voter list this person was validated against', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.registeredvoter'),
        ),
    ]
